#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CreditCardValidator.Droid.Resource", IsApplication=true)]

namespace CreditCardValidator.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Icon = 2130771968;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int creditCardNumberText = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int errorMessagesText = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int validateButton = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int validationSuccessMessage = 2130837507;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int CreditCardValidationSuccess = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int activity_main = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int activity_success = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int credit_card_number_hint = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int credit_card_validation_success_message = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int credit_card_validation_success_name = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int validate_credit_card_label = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
